homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 25
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customizations

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Set recorder options
recorder:
  purge_interval: 3
  purge_keep_days: 7

# Enables configuration UI
config:

# auth_providers:
#  - type: legacy_api_password
#    api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# System Health
system_health:

# Text to speech
tts:
  platform: google_translate

##ZWave Devices
zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 60000
  autoheal: true

# RFXCOM
rfxtrx:
  device: /dev/ttyUSB0
  debug: True

# IOS component
ios:

# include_dir_named: maps filename => content of file.
shell_command: !include_dir_named shell_commands
input_boolean: !include_dir_named input_booleans
input_select: !include_dir_named input_selects
script: !include_dir_named scripts
group: !include_dir_named groups

# include_dir_list: Will return the content of a directory as a list with each file content being an entry in the list.
sensor: !include_dir_list sensors
binary_sensor: !include_dir_list binary_sensors
scene: !include_dir_list scenes
camera: !include_dir_list cameras
# device_tracker: !include_dir_list device_trackers
switch: !include_dir_list switches
automation: !include_dir_list automations
media_player: !include_dir_list media_players
#image_processing: !include_dir_list image_processing
notify: !include_dir_list notifiers

unifi:
  controllers:
    - host: unifi
      site: 192.168.1.22
      ssid_filter:
        - 'AC'
        - 'AC_INTERNAL'

logger:
  default: info
  logs:
    # homeassistant.components.camera: critical
    homeassistant.core: warning
    homeassistant.components.media_player.spotify: info
    homeassistant.components.http: error
    homeassistant.components.image_processing: debug
    homeassistant.components.zwave: error
    homeassistant.components.websocket_api: error
    homeassistant.components.rfxtrx: info
    homeassistant.components.libopenzwave: info
    homeassistant.components.openzwave: info
    custom_components.camera.opencv: debug
